[package]
name = "conway"
version = "0.1.0"
authors = ["Dustin Rohde <dustin.rohde@gmail.com>"]

[dependencies]
clap = "2.32.0"
num-integer = "0.1.39"
lazy_static = "1.0.*"

[dev-dependencies]
maplit = "1.0.1"
